-- database/migrate_security.sql
-- DEPRECATED: All security-hardening schema changes are now handled
-- idempotently by database/schema.sql, which runs automatically on every
-- API startup (see backend/utils/migrate.js). No manual migration needed.
